### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by vkammerer** [creativecreatorormaybenot/wakelock#15]
Hello and thank you for your plugin,

I have just a quick question regarding the name of your plugin: I need to use an actual [wake lock](https://developer.android.com/training/scheduling/wakelock#cpu) which, in Android's vocabulary, is something very different from keeping the screen on. 
So my only question is: is your plugin properly named? I see it is an adaptation of [screen](https://pub.dev/packages/screen) , which is somehow better named :)

**Comment by creativecreatorormaybenot** [comment]
Hi, thank you for your question. See #1 for more details. If you wish to have support for actual wake locks, maybe we can start that discussion again. The problem I see is that it cannot really be utilized in Flutter itself, which is why you would probably do that in Android.

Regarding the name: I think it is fine. I see that Android naming is slightly different, but `screen` is way too broad (and was already used). Web support would also be an option and for web, wakelock would only refer to keeping the screen on as well.

I hope the [description of the plugin](https://pub.dev/packages/wakelock) makes it clear 👍

**Comment by vkammerer** [comment]
Thank you for the quick reply! it's nice to see a plugin well maintained, as this is often not the case. I am currently doing a POC of a Flutter plugin that would enable me to keep a wake lock from an isolate launched from the android alarm manager plugin. If that works well, I would be happy to share with you the code and discuss wether it would be relevant to include it in your plugin's API.

**Comment by creativecreatorormaybenot** [comment]
@vkammerer It sounds good. I will close this question for now. Feel free to open another issue when you are ready 👍

**Comment by ened** [comment]
@vkammerer exactly our use case. We have a background service that starts a Flutter Isolate. Currently, the service is doing the wake lock management though, so I'm not sure what the benefit would be, as in - the consequence of giving up the wake lock would be the termination of the isolate.
