### ISSUE TITLE
Overrides idleTimerDisabled setting of other iOS plugins

### ISSUE THREAD

**Issue by saibotma** [creativecreatorormaybenot/wakelock#154]
Steps to reproduce:
- Download the example app of https://pub.dev/packages/jitsi_meet_wrapper
- Add `wakelock` (0.5.6) as a dependency
- Set device auto lock time to a minimum
- Launch a Jitsi Meeting and wait some minutes
- Screen will dim

Does not happen when `wakelock` dependency is removed.

**Comment by creativecreatorormaybenot** [comment]
Hi @saibotma, thanks for reporting this issue!

I assume this is because of: https://github.com/creativecreatorormaybenot/wakelock/blob/0a6e8c53125847db31a0494a1662c1bcf719fba8/wakelock/ios/Classes/WakelockPlugin.m#L17

Which triggers: https://github.com/creativecreatorormaybenot/wakelock/blob/0a6e8c53125847db31a0494a1662c1bcf719fba8/wakelock/ios/Classes/IdleTimerDisabledObserver.m#L24

Do you have an idea **why** this creates the conflict and how to resolve this? Any contribution is more than welcome as well 👍

**Comment by saibotma** [comment]
It seems like you are enabling the timer when you want to disable it, don't you?

**Comment by creativecreatorormaybenot** [comment]
@saibotma I am not sure - I am fairly confident the current logic works correctly for the plugin.

**Comment by creativecreatorormaybenot** [comment]
@saibotma Can you check if this is still an issue with the latest version (`0.6.1`)?

**Comment by creativecreatorormaybenot** [comment]
I will close this for now since the code has been completely reworked. This might still be an issue. In that case, I will be glad to reopen it :v:
