### ISSUE TITLE
Wakelock is different  on iOS and Android

### ISSUE THREAD

**Issue by KiritoBeater** [creativecreatorormaybenot/wakelock#63]
Wakelock is different  on iOS and Android. I think may be add a comment on code or solve them.

1.  [iOS: idleTimerDisabled = YES works only until ImagePicker was used](https://stackoverflow.com/questions/23391564/ios-idletimerdisabled-yes-works-only-until-imagepicker-was-used)

    On iOS, wakelock.enable() will be change to `false` after UIImagePickerController disappears. This usually happens when the user used the camera

2. When `Add Flutter to existing app`, the Application can have multiple different activities (on Android) or ViewControllers (on iOS) created by the Flutter Engine. Unfortunately，on Android, the Wakelock is for a Activity and on iOS, it is for a whole application

**Comment by creativecreatorormaybenot** [comment]
Thanks a lot for reporting this issue @KiritoBeater 🙂

What exactly would you say is the issue in both of the cases?

1. What is the problem here from the perspective of the `wakelock` plugin as in what could be done differently?
2. I think you can only set the wakelock on an activity on Android, so what should be done differently?

**Comment by KiritoBeater** [comment]
I create a PR, use KVO to resolve the first question. And for the second，I think maybe it need to listen a lifecycle in DartCode
